# Generated by Django 6.1.1 on 2026-09-25 12:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoversationMessage',
            new_name='ConversationMessage',
        ),
    ]
